"""Add rate limiting fields for password reset

Revision ID: 42488be19386
Revises: 1f0255a59c06
Create Date: 2025-10-10 00:40:06.578559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42488be19386'
down_revision = '1f0255a59c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_reset_attempt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_reset_attempt')
        batch_op.drop_column('reset_attempts')

    # ### end Alembic commands ###
