"""Add is_admin field to User model

Revision ID: 9ba7658b0f5c
Revises: 42488be19386
Create Date: 2025-10-14 01:09:46.618346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba7658b0f5c'
down_revision = '42488be19386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # Update all existing records to have is_admin = False
    op.execute("UPDATE user SET is_admin = 0 WHERE is_admin IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
