"""add password_changed_at field to user model

Revision ID: e70aeb2a8181
Revises: 9ba7658b0f5c
Create Date: 2025-10-14 02:26:45.186458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70aeb2a8181'
down_revision = '9ba7658b0f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_changed_at')

    # ### end Alembic commands ###
